language: ruby
rvm:
  - "2.3.0"

notification:
  email: false

script:
- bundle exec rake db:create
- bundle exec rake db:migrate

#only for master
deploy:
  provider: heroku
  api_key:
    secure: "dc4adac0-6490-4e98-b3f0-aa1adafd0ee8"
    app: serlertest
  #on:
  #    all_branches: true

  run:
    - "rake heroku:secrets RAILS_ENV=production"
    - "rake db:create:all"